// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolApp.Repository.Contexts;

namespace SchoolApp.Repository.Migrations
{
    [DbContext(typeof(SchoolAppDbContext))]
    [Migration("20200416094410_RefactorRelationships")]
    partial class RefactorRelationships
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SchoolApp.Repository.Models.CourseDto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("headerTeacherid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("subjectid")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("headerTeacherid");

                    b.HasIndex("subjectid");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.EnrollmentDto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("studentid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("studyPlanid")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("studentid");

                    b.HasIndex("studyPlanid");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.SchoolDto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.StudentDto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("firstName")
                        .HasColumnType("text");

                    b.Property<string>("identificationNumber")
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .HasColumnType("text");

                    b.Property<Guid>("schoolId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.StudentEnrolledInCourseDto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourseDtoid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("enrollmentid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("studentid")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("CourseDtoid");

                    b.HasIndex("enrollmentid");

                    b.HasIndex("studentid");

                    b.ToTable("StudentEnrolledInCourses");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.StudyPlanDetailDto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<Guid>("studyPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("subjectId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("studyPlanId");

                    b.HasIndex("subjectId");

                    b.ToTable("StudyPlanDetails");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.StudyPlanDto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<Guid>("schoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("year")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.SubjectDto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.TeacherDto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourseDtoid")
                        .HasColumnType("uuid");

                    b.Property<string>("firstName")
                        .HasColumnType("text");

                    b.Property<string>("identificationNumber")
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .HasColumnType("text");

                    b.Property<Guid>("schoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("teacherIdentification")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("CourseDtoid");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.CourseDto", b =>
                {
                    b.HasOne("SchoolApp.Repository.Models.TeacherDto", "headerTeacher")
                        .WithMany()
                        .HasForeignKey("headerTeacherid");

                    b.HasOne("SchoolApp.Repository.Models.SubjectDto", "subject")
                        .WithMany()
                        .HasForeignKey("subjectid");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.EnrollmentDto", b =>
                {
                    b.HasOne("SchoolApp.Repository.Models.StudentDto", "student")
                        .WithMany()
                        .HasForeignKey("studentid");

                    b.HasOne("SchoolApp.Repository.Models.StudyPlanDto", "studyPlan")
                        .WithMany()
                        .HasForeignKey("studyPlanid");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.StudentEnrolledInCourseDto", b =>
                {
                    b.HasOne("SchoolApp.Repository.Models.CourseDto", null)
                        .WithMany("studentsEnrolled")
                        .HasForeignKey("CourseDtoid");

                    b.HasOne("SchoolApp.Repository.Models.EnrollmentDto", "enrollment")
                        .WithMany()
                        .HasForeignKey("enrollmentid");

                    b.HasOne("SchoolApp.Repository.Models.StudentDto", "student")
                        .WithMany()
                        .HasForeignKey("studentid");
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.StudyPlanDetailDto", b =>
                {
                    b.HasOne("SchoolApp.Repository.Models.StudyPlanDto", "studyPlan")
                        .WithMany()
                        .HasForeignKey("studyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Repository.Models.SubjectDto", "subject")
                        .WithMany()
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolApp.Repository.Models.TeacherDto", b =>
                {
                    b.HasOne("SchoolApp.Repository.Models.CourseDto", null)
                        .WithMany("secondaryTeachers")
                        .HasForeignKey("CourseDtoid");
                });
#pragma warning restore 612, 618
        }
    }
}
